apiVersion: apps/v1i
kind: StatefulSet
metadata:
  name: prometheus-server
spec:
  serviceName: prometheus-service
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus-server
          image: ubuntu/prometheus
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus
              mountPath: /params
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus
          hostPath:
            path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30098
  type: NodePort
